feat: start server via npx
mhassan1/redis-memory-server pull request #1
Opened 2021-08-25 02:27 UTC by lichangwei

add a simple way to start redis memory server

2021-08-30 02:30 UTC, mhassan1 commented
thanks for the contribution!

this is an interesting idea. what is the use case for this?

2021-09-26 00:50 UTC, shimondoodkin commented
I can imagine the use case for it could be for tests in a not installed environment liked docker. 

maybe to use with not javascript tests.

for example to run it as a background process to have a server.
 
RUN npx cross-env REDISMS_PORT=6379 npx redis-memory-server & 
RUN run c++ tests..

2022-07-13 14:55 UTC, mhassan1 commented
That makes sense. @lichangwei, there is some outstanding feedback.

2023-10-18 18:59 UTC, mhassan1 requested changes

2023-10-18 19:02 UTC, mhassan1 commented
@lichangwei It looks like I never submitted the feedback I wrote over 2 years ago... Sorry about that! It's submitted now.

2023-10-27 11:30 UTC, lichangwei commented on package.json
> +  "bin": "bin/index.js",
fixed

2023-10-27 11:30 UTC, lichangwei commented on README.md
> +### Start server via npx
fixed.

2023-10-27 11:31 UTC, lichangwei commented on bin/index.js
> +})();
fixed

2023-10-27 14:13 UTC, mhassan1 approved these changes

2023-10-27 14:14 UTC, mhassan1 commented
thank you for the contribution, @lichangwei!

2023-10-27 14:14 UTC, merged